# ~/.config/fish/config.fish

# set -q __fish_home_manager_config_sourced; and exit
# set -g __fish_home_manager_config_sourced 1

# source ./hm-session-vars.fish

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations

    # Aliases

    # Interactive shell initialisation
    source $HOME/.config/fish/base16-catppuccin-mocha.fish

    # See https://github.com/tomyun/base16-fish/issues/7 for why this condition exists
    if status --is-interactive && test -z "$TMUX"
        base16-catppuccin-mocha
    end

    zoxide init fish | source

    if test "$TERM" != dumb
        starship init fish | source

    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        # set fish_complete_path $prev "/home/makano/.local/share/fish/home-manager/generated_completions" $post
    end

    carapace _carapace fish | source

    direnv hook fish | source

end
